name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_script: 'electron:build'
            build_args: '--linux'
          - os: macos-latest
            build_script: 'electron:build'
            build_args: '--mac'
          - os: windows-latest
            build_script: 'electron:build'
            build_args: '--win'

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          build_script_name: ${{ matrix.build_script }}
          args: ${{ matrix.build_args }}
